apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: db:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: postgresql/
    git:
      ref: openshift
      uri: https://git.muenchen.de/lhm-udp-katalog-2/ckan-docker-ga.git
    type: ""
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
      env:
        - name: DATASTORE_READONLY_PASSWORD
          value: datastore
        - name: POSTGRES_PASSWORD
          value: ckan
    type: ""
  triggers:
    - type: ConfigChange
status:
  lastVersion: 0
