apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ckan-solr-pvc
  name: ckan-solr-pvc
  namespace: udpkatalog-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
status: {}
