apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: datapusher
  name: datapusher
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ckan/ckan-base-datapusher:0.0.20
      generation: null
      importPolicy: {}
      name: 0.0.20
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
