apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: redis:6
      generation: null
      importPolicy: {}
      name: "6"
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
