apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: solr
  name: solr
  namespace: udpkatalog-dev
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ckan/ckan-solr:2.10-spatial
      generation: null
      importPolicy: {}
      name: 2.10-spatial
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
