apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ckan
  name: ckan
  namespace: udpkatalog-dev
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ckan
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""

---

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
  namespace: udpkatalog-dev
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: db
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""

---

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
  namespace: udpkatalog-dev
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: nginx
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""

---

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: datapusher
  name: datapusher
  namespace: udpkatalog-dev
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ckan/ckan-base-datapusher:0.0.20
      generation: null
      importPolicy: {}
      name: 0.0.20
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""

---

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
  namespace: udpkatalog-dev
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: redis:6
      generation: null
      importPolicy: {}
      name: "6"
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""

---

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: solr
  name: solr
  namespace: udpkatalog-dev
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ckan/ckan-solr:2.10-spatial
      generation: null
      importPolicy: {}
      name: 2.10-spatial
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""

---

